// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restful.Data;

#nullable disable

namespace Restful.Migrations.DepartmentEmployeeAPIDb
{
    [DbContext(typeof(DepartmentEmployeeAPIDbContext))]
    partial class DepartmentEmployeeAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Restful.Models.Department_EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Department_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DepartmentEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
